version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    container_name: bored-bot
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1